### ISSUE TITLE
establish new branch rules for repos

### ISSUE THREAD

**Issue by endepointe** [SecurityLogMiner/log-collection-backend#26]
A free for all isnt going to work when pushing and pulling code changes. A single person will have to be in charge of a repo and have branch control. This will ensure code quality while not preventing people from writing their own code branch.

I suggest we include branch protection rules that require the review of one person for each repo. 

I will take the client repo if no one minds. That leaves the server branch and frontend. We may need another branch for documentation as well.

**Comment by Jicxer** [comment]
I am free to take any of the branches. What would it entail if one person owns a branch? Would this part of the "A" branch that we discussed that rests upstream from the features branches?

**Comment by endepointe** [comment]
Still need to figure out how to add a rule the requires the specific review of an code owner. I will look some more either later tonight or tomorrow

**Comment by josnhal** [comment]
There is one code owner now - josnhal. I would rather us create an admin account that we all have access to. We can decide that later on. I made these changes so that the admins below have control over merges to corresponding repos. 

[See](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews)

- Jicxer is the frontend admin.
- murchej is the server admin.
- endepointe is the client admin.
- khuynh2002 is documentation admin

**Comment by endepointe** [comment]
documentation and client repos have protection and rulsets in place.

**Comment by josnhal** [comment]
added branch rule for server branch. download the ruleset for future branches (attached)

[developement protection.json](https://github.com/SecurityLogMiner/log-collection-client/files/13663779/developement.protection.json)
